language: java
jdk:
- openjdk8

# http://docs.travis-ci.com/user/caching/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  # https://docs.travis-ci.com/user/sonarcloud/
  sonarcloud:
    organization: "marcelstoer-github"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
- mvn clean test jacoco:report coveralls:jacoco

env:
  secure: "M3lwBU5o8ZFIa9mILmKAJvQr7l/jDbP6/wa8y9fISfrFI6L439glBcKa+6ZnwA9eGw0szhGfS/f6V33j5oM8K8cTHxSsavMM1+rSCjDbUrxOX9102W7iNlprdzuhItL8hVlAUNQXwqrqrJozmHT2iioSXbNkI/eRSD7cPQ6+q1I="
