# Use Docker-based build environment (instead of OpenVZ) as per http://goo.gl/TxCoVM
sudo: false

language: java
jdk:
- oraclejdk7
- openjdk7

# http://docs.travis-ci.com/user/caching/
cache:
  directories:
    - '$HOME/.m2/repository'

after_success:
- mvn clean test jacoco:report coveralls:jacoco

env:
  secure: "M3lwBU5o8ZFIa9mILmKAJvQr7l/jDbP6/wa8y9fISfrFI6L439glBcKa+6ZnwA9eGw0szhGfS/f6V33j5oM8K8cTHxSsavMM1+rSCjDbUrxOX9102W7iNlprdzuhItL8hVlAUNQXwqrqrJozmHT2iioSXbNkI/eRSD7cPQ6+q1I="
